---
name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: ghcr.io/ibis-ssl/docker-ros2-images:humble
    steps:
      - name: install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget python3-jenkinsapi ca-certificates curl

      - name: Install docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo chmod +x ./get-docker.sh
          ./get-docker.sh


      - name: fix setup script to avoid error
        run: sudo sed -i 's/ulimit -Hn 524288/ulimit -n 524288/g' /etc/init.d/docker
        # https://forums.docker.com/t/etc-init-d-docker-62-ulimit-error-setting-limit-invalid-argument-problem/139424
        
      - name: make workspace
        run: mkdir -p /root/ros2_ws/src

      - name: get repos
        run: |
          cd /root/ros2_ws
          wget https://raw.githubusercontent.com/HansRobo/colcon-ros-buildfarm/refs/heads/devel-customized/crb.repos

      - name: colcon build
        run: |
          # service docker start
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          vcs import src < crb.repos
          rosdep update
          rosdep install -riy --from-paths src
          colcon build
        shell: bash

      - name: run buildfarm
        run: |
          source /root/ros2_ws/install/setup.bash
          ros_buildfarm release --continue-on-error --config-url https://raw.githubusercontent.com/HansRobo/colcon-ros-buildfarm/refs/heads/devel-customized/ros_buildfarm_config/index.yaml
        shell: bash
  build_docker:
    name: build docker
    runs-on: ubuntu-latest
    steps:
      - name: Install docker for ubuntu runner
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: HansRobo/colcon_ros_buildfarm:latest
