---
name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build_docker:
    name: build docker
    runs-on: ubuntu-latest
    steps:
      - name: Install docker for ubuntu runner
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: HansRobo/colcon_ros_buildfarm:latest
